### PR TITLE
Add organization README

### PR DESCRIPTION
**Pull request by flavio**
WIP

[Rendered version](https://github.com/kubewarden/.github/blob/add-org-readme/profile/README.md)

### CODE REVIEW

**Comment by flavio** [comment]
gosh, this is too long... I'll trim it down :scissors:

**Review by olblak — APPROVED** [review]
That's a great organization README.

**Comment by olblak** [comment]
Maybe you could just keep the following section and conclude with a link to Contributing. 

* About Kubewarden
* Getting started
* Getting in touch

**Comment by flavio** [comment]
I've done quite some changes, I tried to use a completely different style

**Comment by flavio** [comment]
Merging as discussed during the daily

**Comment by olblak** [comment]
> I've done quite some changes, I tried to use a completely different style

Indeed that's a different style :p. I like that we have a quick idea of what is Kubewarden and how to use it. I am just wondering if the "Useful GitHub Tag" is needed. My understanding is that the person who reads that page, is a developer who arrived at the organization level and is interested to understand what Kubewarden is and where to find repository information.
To me, the most important informations are :

1. What is Kubewarden
2. Where to go for contributing
3. Who to contact for contributing

IMHO any additional information should be more detailed in specific documentation.

**Comment by flavio** [comment]
Thanks for the feedback! Let's talk more about that during one of our dailies/the planning session

**Pull request merged**
