### PR TITLE
fix(docs): update/correct .NET links

### PR DESCRIPTION
**Pull request by agilgur5**
## Description

Update and correct the .NET  SDK and template links
- the [policy template](https://github.com/kubewarden/dotnet-policy-template) wasn't linked
- the [policy SDK](https://github.com/kubewarden/policy-sdk-dotnet) incorrectly linked to the Rust one

- misc `markdownlint` newline autofixes

## Test

See the rendered markdown [rich diff](https://github.com/kubewarden/.github/pull/19/files?short_path=0e83982#diff-0e83982cf6f4dabedcbf7b12029a56c6f4a728064ba99543fff8f227c0654b45)

### Tradeoff

n/a

### Potential improvement

n/a

### CODE REVIEW

**Comment by agilgur5** [comment]
Related:
- I wasn't really sure what the icons for "Maturity" meant in the table
- It is a little confusing to have some docs on this page and some in the [docs site](https://docs.kubewarden.io/tutorials/writing-policies); might make sense to link out and consolidate a bit
- [Kyverno](https://github.com/kubewarden/kyverno-dsl-policy) and [CEL](https://github.com/kubewarden/cel-policy) aren't mentioned here, should they be? They're also missing the [`kubewarden-policy`](https://github.com/topics/kubewarden-policy) GH topic tag. The [Go WASI template](https://github.com/kubewarden/go-wasi-policy-template) also isn't in the table and is missing the GH topic tag for [`kubewarden-policy-template`](https://github.com/topics/kubewarden-policy-template)

**Comment by flavio** [comment]
Thanks for bringing awareness about this issue. This contents have been created a long time ago, before we were suggested by CNCF to use a different model to keep track of the contents of our repositories. That resulted with the creation of [this repository](https://github.com/kubewarden/community) and, most important, [this section](https://github.com/kubewarden/community?tab=readme-ov-file#repositories).

I think we should revisit the contents of the `README.md` of this repository to avoid duplicated and conflicting contents.

@kubewarden/kubewarden-developers what do the other maintainers think about that?

**Comment by viccuad** [comment]
> I think we should revisit the contents of the README.md of this repository to avoid duplicated and conflicting contents.

Agree! I think pointing to kubewarden/community is saner here.

**Comment by fabriziosestito** [comment]
> > I think we should revisit the contents of the README.md of this repository to avoid duplicated and conflicting contents.
> 
> Agree! I think pointing to kubewarden/community is saner here.

+1

**Comment by jvanz** [comment]
> > I think we should revisit the contents of the README.md of this repository to avoid duplicated and conflicting contents.
> 
> Agree! I think pointing to kubewarden/community is saner here.

+1

**Comment by flavio** [comment]
Thanks for the feedback, everybody agrees about the removal of this section from the README. We will replace it with a link to the community repository.

@agilgur5 we can handle that on our own if you don't want to make this change.

**Comment by agilgur5** [comment]
I can close this PR (as it would no longer be .NET related nor a fix) and open another to significantly condense this section -- I would just point to the ["Writing Policies" docs page](https://docs.kubewarden.io/tutorials/writing-policies) IMO. There's already a link to the community repository [above this in "Getting Started"](https://github.com/kubewarden/.github/blob/5629e838466ebd35fdb426ae21b57f59002ef0bb/profile/README.md?plain=1#L10).

> * [Kyverno](https://github.com/kubewarden/kyverno-dsl-policy) and [CEL](https://github.com/kubewarden/cel-policy) aren't mentioned here, should they be? They're also missing the [`kubewarden-policy`](https://github.com/topics/kubewarden-policy) GH topic tag. The [Go WASI template](https://github.com/kubewarden/go-wasi-policy-template) also isn't in the table and is missing the GH topic tag for [`kubewarden-policy-template`](https://github.com/topics/kubewarden-policy-template)

Are the GH tags still accurate in the section below this? I noticed Kyverno was also missing from the `community` repo, but the others are there. I can open a PR to add the Kyverno policy in the `community` repo listing, but the tags require action from folks who have write permissions (can't PR changes to that unfortunately 😅 ).

**Comment by agilgur5** [comment]
> I can close this PR (as it would no longer be .NET related nor a fix) and open another to significantly condense this section -- I would just point to the ["Writing Policies" docs page](https://docs.kubewarden.io/tutorials/writing-policies) IMO.

See #20 as a superseding PR

**Comment by agilgur5** [comment]
> > * [Kyverno](https://github.com/kubewarden/kyverno-dsl-policy) and [CEL](https://github.com/kubewarden/cel-policy) aren't mentioned here, should they be? They're also missing the [`kubewarden-policy`](https://github.com/topics/kubewarden-policy) GH topic tag. The [Go WASI template](https://github.com/kubewarden/go-wasi-policy-template) also isn't in the table and is missing the GH topic tag for [`kubewarden-policy-template`](https://github.com/topics/kubewarden-policy-template)
> 
> Are the GH tags still accurate in the section below this? I noticed Kyverno was also missing from the `community` repo, but the others are there. I can open a PR to add the Kyverno policy in the `community` repo listing, but the tags require action from folks who have write permissions (can't PR changes to that unfortunately 😅 ).

It seems like the GH tags are still accurate since that wasn't changed, so I opened a few issues to cover the GH topic tags as todos: https://github.com/kubewarden/cel-policy/issues/100, https://github.com/kubewarden/kyverno-dsl-policy/issues/50, https://github.com/kubewarden/go-wasi-policy-template/issues/68

And PR to add Kyverno policy to the `community` repo: https://github.com/kubewarden/community/pull/25

**Pull request closed without merging**
